version: "2"
services:
  taavoni:
    container_name: taavoni_app
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo:taavoni_mongodb
  mongo:
    container_name: taavoni_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"